#Issue101 - Add store html checkbox value and apply for all views.
MichaelCurrin/badge-generator pull request #135
Opened 2021-11-26 04:13 UTC by irenejoeunpark

This PR is an additional feature to issue #101. 
Created method to store asHtml in store.ts and use that value in Code.vue.
If you check/uncheck the Html checkbox in one view, it applies to all other views.

2021-11-26 19:31 UTC, MichaelCurrin commented on src/store.ts
> +// import  asHtml from "@/components/Code.vue";
```suggestion
```

2021-11-26 19:32 UTC, MichaelCurrin commented on tests/unit/components/Code.spec.ts
> +import store from "@/store";
```suggestion
```

2021-11-26 19:32 UTC, MichaelCurrin commented on tests/unit/components/Code.spec.ts
> +
```suggestion
```

2021-11-26 19:36 UTC, MichaelCurrin commented on tests/unit/components/Code.spec.ts
> +import store from "@/store";
Add tests to `store.spec.ts` rather

2021-11-26 20:13 UTC, MichaelCurrin commented on tests/unit/components/Code.spec.ts
> +import store from "@/store";
This bit needs to be actually used.

Also please run tests and fix them. The Code component needs to switch between HTML and Markdown mode in the tests.

This file is failing.

This old code is like this:

```
      data() {
        return {
          asHtml: true,
        };
      },
```
 

I tried adding this and it didn't work.
```

    wrapper.setData({ asHtml: true })
    store.setAsHtml(true)
```

2021-11-26 20:13 UTC, MichaelCurrin requested changes
fix failing tests

2021-11-26 20:19 UTC, MichaelCurrin commented
Also an problem I found is that the checkbox only syncs across views - I'd like it to sync _within_ the Catalogue view across checkboxes.

So maybe the asHtml boolean is passed in as a prop to the component. That will make the tests easier.
And also then the Catalogue page can have an asHtml value which is passed to all components, so they all share the same value. Events will be needed to sync them.

I tried this global approach but had errors

https://stackoverflow.com/a/54882568/6250733

2021-11-29 15:52 UTC, irenejoeunpark commented
> Also an problem I found is that the checkbox only syncs across views - I'd like it to sync _within_ the Catalogue view across checkboxes.
> 
> So maybe the asHtml boolean is passed in as a prop to the component. That will make the tests easier. And also then the Catalogue page can have an asHtml value which is passed to all components, so they all share the same value. Events will be needed to sync them.
> 
> I tried this global approach but had errors
> 
> https://stackoverflow.com/a/54882568/6250733



> Also an problem I found is that the checkbox only syncs across views - I'd like it to sync _within_ the Catalogue view across checkboxes.
> 
> So maybe the asHtml boolean is passed in as a prop to the component. That will make the tests easier. And also then the Catalogue page can have an asHtml value which is passed to all components, so they all share the same value. Events will be needed to sync them.
> 
> I tried this global approach but had errors
> 
> https://stackoverflow.com/a/54882568/6250733

Thanks for noticing those! I will give you a fix as soon as I finish them.
And how do I run the test?

2021-11-29 23:06 UTC, MichaelCurrin commented
https://github.com/MichaelCurrin/badge-generator/blob/master/docs/usage.md#tests

Or on Windows 

```
yarn test
```

Also note the checks at the bottom of the conversation with green ticks and then a red cross for the failing tests on GitHub Actions

2022-01-06 13:03 UTC, MichaelCurrin commented
Let me know if you need more info to complete this. Thanks.

2025-05-24 04:46 UTC, nareshrajkumar866 approved these changes

2026-06-22 08:25 UTC, closed without merging